### ISSUE TITLE
Setting debug to true sometimes causes hanging with issuing commands

### ISSUE THREAD

**Issue by ghost** [Vaelor/python-mattermost-driver#25] opened 2018-03-13 20:36 UTC
Here is the code that I have:

```
# mattermost driver settings
driver = Driver({
        'url': '<url>',
        'login_id': '<email>',
        'password': '<password>',
        'port': <port>,
        'debug': True,
})

# log into mattermost
driver.login()

# make a post in mattermost
driver.posts.create_post(options={
        'channel_id': '<id>',
        'message': '<message>'
})
```

When using this code, the driver.posts.create_post method sometimes hangs indefinitely without any debug output. It is seemingly random as to when this happens.

**Comment by Vaelor** [comment] 2018-03-14 10:18
That is strange, I will try to reproduce the issue.
Does this happen with any message, or are these messages very long?

**Comment by Vaelor** [comment] 2019-03-12 14:11
Closing, since the user who created the issue has deleted his account and I never got any feedback/couldn't reproduce.

**Closed by Vaelor** 2019-03-12 14:11 UTC
