### ISSUE TITLE
Very first websockets.pong() call seems to fail

### ISSUE THREAD

**Issue by attzonko** [Vaelor/python-mattermost-driver#79] opened 2021-03-19 23:35 UTC
Hi, we are using this driver for our bot code, and are seeing some weird behavior (See details here: https://github.com/attzonko/mmpy_bot/issues/171)

On the Mattermost server side, I am seeing an invalid character error from the first `websockets.pong()` future after the 20s timeout.
```
{"level":"debug","ts":1616195215.1219645,"caller":"app/web_conn.go:190","msg":"Error while reading message from websocket","error":"error during decoding websocket message: invalid character 'ð' looking for beginning of value","errorVerbose":"invalid character 'ð' looking for beginning of value\nerror during decoding websocket message\ngithub.com/mattermost/mattermost-server/v5/app.(*WebConn).ReadMsg\n\tgithub.com/mattermost/mattermost-server/v5/app/web_conn.go:257\ngithub.com/mattermost/mattermost-server/v5/app.(*WebConn).startPoller.func1.1\n\tgithub.com/mattermost/mattermost-server/v5/app/web_conn.go:188\nruntime.goexit\n\truntime/asm_amd64.s:1374"}
```

Any ideas on what we could be doing wrong? Or is this possibly a real issue?

**Comment by attzonko** [comment] 2021-03-20 00:02
Looking a bit deeper it seems the internal ping generated from websockets is what is generating an invalid character. Your code eventually times out and tries to send a `pong()` but by then the connection is severed.

Further, it seems the data sent as part of the `ping()` changes each time I see the issue reproduced.

**Comment by Vaelor** [comment] 2021-03-21 14:59
Hey @attzonko

I have to admit I am not sure what is causing that, but I couldn't really reproduce it on my end yet.
My reproduction code is fairly easy, as I just did the following

```
foo = Driver({'debug': True, 'url': '', 'login_id': '', 'password': '', 'verify': False, 'port': 443})
foo.login()
foo.init_websocket(testmessage)
```

And then I just waited for the pong to appear and observed logs (both debug) and I haven't seen any such error occuring so far.

**Comment by attzonko** [comment] 2021-03-22 16:57
We still have not figured out why the issue seems reproducible by only a few folks. I wonder if it is somehow related to a newer version of GO libraries on the MM side. It seems the `ping()` is sending binary data as expected but the MM side is expecting something it shouldn't. https://github.com/aaugustin/websockets/issues/922

We are still trying to figure out the root cause and how we might fix/patch the issue.

**Comment by tobika** [comment] 2021-03-22 17:04
Had the same problem, it seems to be fixed with a mattermost version that was released just today, not tested yet ;-)

https://mattermost.atlassian.net/browse/MM-34000
https://docs.mattermost.com/administration/changelog.html (5.33.1)

**Comment by tobika** [comment] 2021-03-22 18:00
@attzonko sorry, at least for me it was false hope, the update to 5.33.1 didn't change anything

**Comment by attzonko** [comment] 2021-03-22 18:35
Closing this as it is not an issue with this repo. Thanks!

**Comment by Vaelor** [comment] 2021-03-22 18:46
That explains why I couldn't reproduce it, I was still on 5.31.0 with my testserver.

I hope you can get it sorted out :-)

**Comment by attzonko** [comment] 2021-03-24 21:04
I think to fully lay this to rest we should wait until #86 is merged and a new release available.

**Closed** 2022-02-27 21:27 UTC
